### ISSUE TITLE
can I use it in the Hugo project when using Hugo server?

### ISSUE THREAD

**Issue by ghost** [davidgs/Translator#9]
Is it something one can use in Hugo project or it needs to run on a server? If you have a demo repo demonstrating this will be great help.

**Comment by davidgs** [comment]
I don't think this would be appropriate for using in `hugo server` commands. It's best used in a GitHub action when you are creating a PR 

```
# This is a basic workflow to help you get started with Actions

name: validate

# Controls when the action will run.
on:
  push:
    branches:
      - '**'         # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web Repo
        uses: actions/checkout@v5
        with:
          repository: davidgs/YOUR_SITE_REPO
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: ./YOUR_SITE_REPO
      - name: Checkout Translate
        uses: actions/checkout@v5
        with:
          repository: davidgs/Translator
          path: ./translate
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'
          extended: true
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
      - name: Build Translator
        run: cd ./translate; go build translate.go
      - name: Create Secret
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "./translate/google-secret.json"
          json: ${{ secrets.TRANSLATE_SECRET }}
      - name: Translate
        run: cd ./translate; ./translate ../YOUR_SITE_REPO/content/posts/
      - name: ReCommit
        # run: cd ./YOUR_SITE_REPO
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply Auto-Translations
          # branch: main
          # file_pattern: index.*.md
          repository: ./YOUR_SITE_REPO

```

So when you check in a new post, it will get automatically translated, the translations will be pushed back to the branch, and then committed to the branch
